#!/usr/bin/env python3
"""Generate scripts/tests/COVERAGE.md from the gates themselves.

The previous COVERAGE.md was hand-maintained. It listed per-fixture test classes
(`TestCACHE001` ...) with hardcoded assertion counts, and went stale the moment
the suite was restructured -- claiming coverage that no longer existed, which is
worse than claiming none. Everything here is derived from the live fixtures,
the live rule table, and a live pytest collection, so it cannot drift.

Usage:
  gen_coverage.py            rewrite COVERAGE.md
  gen_coverage.py --check    fail if the committed file is out of date

Exit: 0 ok · 1 out of date (--check) · 3 cannot collect tests
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
TESTS = SKILL_DIR / "scripts" / "tests"
GOLDEN = TESTS / "golden"
OUT = TESTS / "COVERAGE.md"


def load_linter():
    spec = importlib.util.spec_from_file_location(
        "rcs_lint_gen", SKILL_DIR / "scripts" / "lint_cache_docs.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["rcs_lint_gen"] = mod
    spec.loader.exec_module(mod)
    return mod


def count_tests(path: Path) -> int:
    """Collected test count, from pytest itself rather than a maintained number."""
    r = subprocess.run(
        [sys.executable, "-m", "pytest", str(path), "--collect-only", "-q"],
        cwd=SKILL_DIR, capture_output=True, text=True,
    )
    m = re.search(r"(\d+)\s+tests?\s+collected", r.stdout)
    if m:
        return int(m.group(1))
    # pytest prints "N/M tests collected" when deselecting, and a bare count line
    # in some versions; fall back to counting node ids.
    nodes = [ln for ln in r.stdout.splitlines() if "::" in ln]
    if nodes:
        return len(nodes)
    return -1


def build() -> str:
    lint = load_linter()
    fixtures = [json.loads(p.read_text(encoding="utf-8"))
                for p in sorted(GOLDEN.glob("*.json"))]
    n_contract = count_tests(TESTS / "test_skill_contract.py")
    n_golden = count_tests(TESTS / "test_golden_scenarios.py")
    if n_contract < 0 or n_golden < 0:
        raise SystemExit(3)

    mut = (SKILL_DIR / "scripts" / "mutation_sweep.py").read_text(encoding="utf-8")
    n_mutations = len(re.findall(r'^\s*\("M\d+",', mut, re.M))

    go_docs = (SKILL_DIR / "scripts" / "check_go_snippets.py").read_text(encoding="utf-8")

    L: list[str] = []
    a = L.append
    a("# Test Coverage — redis-cache-strategy")
    a("")
    a("<!-- GENERATED by scripts/gen_coverage.py — do not edit by hand. -->")
    a("<!-- Regenerate: python3 scripts/gen_coverage.py -->")
    a("")
    a("## 1. Gates")
    a("")
    a("Run all of them with `bash scripts/run_regression.sh`. A gate that cannot")
    a("run exits 3 and is reported as SKIPPED — never as a pass.")
    a("")
    a("| # | Gate | What it proves |")
    a("|---|------|----------------|")
    a("| 1 | `lint_cache_docs.py --selftest` | Every rule still fires on its own violating input — a dead rule reports \"clean\" |")
    a("| 2 | `lint_cache_docs.py` | Semantic invariants the compiler cannot see |")
    a("| 3 | `check_go_snippets.py` | Every Go snippet in the docs actually compiles |")
    a("| 4 | `test_skill_contract.py` | SKILL.md structure, required sections, reference files |")
    a("| 5 | `test_golden_scenarios.py` | Fixtures drive the real checker, both directions |")
    a("| 6 | `mutation_sweep.py` | Each gate rejects the defect it claims to catch |")
    a("")
    a(f"Collected tests: **{n_contract}** contract · **{n_golden}** golden.")
    a(f"Mutations: **{n_mutations}**. Lint rules: **{len(lint.RULES)}**.")
    a("")

    a("## 2. Lint rules")
    a("")
    a("Declared as data in `lint_cache_docs.py`; `--selftest` asserts each one fires.")
    a("")
    a("| Rule | Scope | Checks |")
    a("|------|-------|--------|")
    for r in lint.RULES:
        a(f"| `{r.id}` | {r.scope} | {r.summary} |")
    a("")

    a("## 3. Golden fixtures")
    a("")
    a("`detectors` are the rules that MUST fire on the snippet — asserted in both")
    a("directions, so an over-broad rule fails too. `gated by` names the rule that")
    a("catches the *headline* defect; `—` means only a model review can, which is")
    a("recorded per fixture rather than left silent.")
    a("")
    a("| ID | Title | Type | Severity | Detectors | Gated by |")
    a("|----|-------|------|----------|-----------|----------|")
    for f in fixtures:
        det = ", ".join(f"`{d}`" for d in f["detectors"]) or "—"
        prim = f"`{f['primary_defect_gated_by']}`" if f["primary_defect_gated_by"] else "—"
        a(f"| {f['id']} | {f['title']} | {f['type']} | {f['severity']} | {det} | {prim} |")
    a("")

    defects = [f for f in fixtures if f["type"] == "defect"]
    gated = [f for f in defects if f["primary_defect_gated_by"]]
    a(f"**{len(gated)}/{len(defects)}** defect fixtures have their headline defect")
    a("mechanically gated. The rest depend on the model reading SKILL.md — that is")
    a("the honest limit of a static gate, stated rather than hidden.")
    a("")

    a("## 4. Go compile gate")
    a("")
    a("`check_go_snippets.py` extracts every ```go block from SKILL.md and")
    a("`references/*.md`, wraps each in a package, and runs `go build`.")
    docs = re.search(r"DOCS\s*=\s*\[(.*?)\]", go_docs, re.S)
    if docs:
        names = re.findall(r'"([^"]+\.md)"', docs.group(1))
        if names:
            a("")
            a("Files covered: " + ", ".join(f"`{n}`" for n in names) + ".")
    a("")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    new = build()
    if args.check:
        old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if old != new:
            print("COVERAGE.md is out of date — run: python3 scripts/gen_coverage.py",
                  file=sys.stderr)
            return 1
        print("COVERAGE.md up to date")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUT.relative_to(SKILL_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
