#!/usr/bin/env python3
"""Generate scripts/tests/COVERAGE.md from the gates themselves.

The previous COVERAGE.md was hand-maintained. It listed per-fixture test classes
(`TestCACHE001` ...) with hardcoded assertion counts, and went stale the moment
the suite was restructured -- claiming coverage that no longer existed, which is
worse than claiming none. Everything here is derived from the live fixtures,
the live rule table, and a live pytest collection, so it cannot drift.

Usage:
  gen_coverage.py            rewrite COVERAGE.md
  gen_coverage.py --check    fail if the committed file is out of date

Exit: 0 ok · 1 out of date (--check) · 3 cannot collect tests
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
TESTS = SKILL_DIR / "scripts" / "tests"
GOLDEN = TESTS / "golden"
OUT = TESTS / "COVERAGE.md"


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def load_linter():
    return load_module("rcs_lint_gen", SKILL_DIR / "scripts" / "lint_cache_docs.py")


# What each gate proves. Keyed by the script the runner invokes, so a gate added
# to run_regression.sh with no entry here is reported as undescribed rather than
# omitted -- the previous version hardcoded six rows while the runner ran seven,
# and the seventh was simply invisible in the coverage doc.
GATE_CLAIMS: dict[str, str] = {
    "lint_cache_docs.py --selftest":
        'Every rule still fires on its own violating input — a dead rule reports "clean"',
    "lint_cache_docs.py": "Semantic invariants the compiler cannot see",
    "check_go_snippets.py": "Every Go snippet in the docs actually compiles",
    "test_skill_contract.py": "SKILL.md structure, scorecard arithmetic, reference TOCs",
    "test_golden_scenarios.py":
        "Fixtures drive the real checker, both directions, and every §5 item a "
        "defect violates can actually affect the score",
    "model_eval.py --calibrate":
        "The model-eval grader separates on each axis independently — offline, no model",
    "trigger_eval.py --check":
        "The routing corpus is well-formed and its negatives are adversarial",
    "mutation_sweep.py": "Each gate rejects the defect it claims to catch",
    "gen_coverage.py --check": "This file is generated from the gates, not maintained by hand",
}


def gates() -> list[tuple[str, str, str]]:
    """(number, gate command, what it proves) parsed from run_regression.sh.

    Derived, not declared: the runner is the only place that decides which gates
    exist, so the table cannot claim a gate that does not run or miss one that does.
    """
    sh = (SKILL_DIR / "scripts" / "run_regression.sh").read_text(encoding="utf-8")
    out: list[tuple[str, str, str]] = []
    for m in re.finditer(
        r'run_gate\s+"(\d+)/\d+[^"]*"\s*\\?\s*\n\s*(.+?)\n', sh, re.M
    ):
        num, cmd = m.group(1), m.group(2).strip()
        cmd = re.sub(r"^python3\s+", "", cmd)
        cmd = re.sub(r"^-m pytest\s+\"?\$\{TEST_DIR\}/", "", cmd)
        cmd = cmd.replace("scripts/", "").replace('"', "").replace(" -q", "")
        out.append((num, cmd, GATE_CLAIMS.get(cmd, "**UNDESCRIBED — add it to GATE_CLAIMS**")))
    return out


def count_tests(path: Path) -> int:
    """Collected test count, from pytest itself rather than a maintained number."""
    r = subprocess.run(
        [sys.executable, "-m", "pytest", str(path), "--collect-only", "-q"],
        cwd=SKILL_DIR, capture_output=True, text=True,
    )
    m = re.search(r"(\d+)\s+tests?\s+collected", r.stdout)
    if m:
        return int(m.group(1))
    # pytest prints "N/M tests collected" when deselecting, and a bare count line
    # in some versions; fall back to counting node ids.
    nodes = [ln for ln in r.stdout.splitlines() if "::" in ln]
    if nodes:
        return len(nodes)
    return -1


def build() -> str:
    lint = load_linter()
    fixtures = [json.loads(p.read_text(encoding="utf-8"))
                for p in sorted(GOLDEN.glob("*.json"))]
    n_contract = count_tests(TESTS / "test_skill_contract.py")
    n_golden = count_tests(TESTS / "test_golden_scenarios.py")
    if n_contract < 0 or n_golden < 0:
        raise SystemExit(3)

    mut = (SKILL_DIR / "scripts" / "mutation_sweep.py").read_text(encoding="utf-8")
    n_mutations = len(re.findall(r'^\s*\("M\d+",', mut, re.M))

    L: list[str] = []
    a = L.append
    a("# Test Coverage — redis-cache-strategy")
    a("")
    a("<!-- GENERATED by scripts/gen_coverage.py — do not edit by hand. -->")
    a("<!-- Regenerate: python3 scripts/gen_coverage.py -->")
    a("")
    a("## 1. Gates")
    a("")
    a("Run all of them with `bash scripts/run_regression.sh`. A gate that cannot")
    a("run exits 3 and is reported as SKIPPED — never as a pass.")
    a("")
    a("| # | Gate | What it proves |")
    a("|---|------|----------------|")
    for num, cmd, claim in gates():
        a(f"| {num} | `{cmd}` | {claim} |")
    a("")
    a(f"Collected tests: **{n_contract}** contract · **{n_golden}** golden.")
    a(f"Mutations: **{n_mutations}**. Lint rules: **{len(lint.RULES)}**.")
    a("")

    a("## 2. Lint rules")
    a("")
    a("Declared as data in `lint_cache_docs.py`; `--selftest` asserts each one fires.")
    a("")
    a("| Rule | Scope | Checks |")
    a("|------|-------|--------|")
    for r in lint.RULES:
        a(f"| `{r.id}` | {r.scope} | {r.summary} |")
    a("")

    a("## 3. Golden fixtures")
    a("")
    a("`detectors` are the rules that MUST fire on the snippet — asserted in both")
    a("directions, so an over-broad rule fails too. `gated by` names the rule that")
    a("catches the *headline* defect; `—` means only a model review can, which is")
    a("recorded per fixture rather than left silent.")
    a("")
    a("| ID | Title | Type | Severity | Detectors | Gated by |")
    a("|----|-------|------|----------|-----------|----------|")
    for f in fixtures:
        det = ", ".join(f"`{d}`" for d in f["detectors"]) or "—"
        prim = f"`{f['primary_defect_gated_by']}`" if f["primary_defect_gated_by"] else "—"
        a(f"| {f['id']} | {f['title']} | {f['type']} | {f['severity']} | {det} | {prim} |")
    a("")

    defects = [f for f in fixtures if f["type"] == "defect"]
    gated = [f for f in defects if f["primary_defect_gated_by"]]
    a(f"**{len(gated)}/{len(defects)}** defect fixtures have their headline defect")
    a("mechanically gated. The rest depend on the model reading SKILL.md — that is")
    a("the honest limit of a static gate, stated rather than hidden.")
    a("")

    a("## 4. Scorecard reachability")
    a("")
    a("Each fixture names the §5 item IDs it violates. A `critical` fixture whose")
    a("worst item sits in a lower tier cannot force a FAIL, so that combination is")
    a("a test failure rather than a footnote.")
    a("")
    a("| Fixture | Severity | §5 items |")
    a("|---------|----------|----------|")
    for f in fixtures:
        if f["type"] != "defect":
            continue
        a(f"| {f['id']} | {f['severity']} | {', '.join(f['scorecard_items']) or '—'} |")
    a("")
    exercised = {i for f in fixtures for i in f["scorecard_items"]}
    items = lint.skill_items((SKILL_DIR / "SKILL.md").read_text(encoding="utf-8"))
    all_ids = [f"{p}{n}" for p in ("C", "S", "H") for n in sorted(items.get(p, []))]
    uncovered = [i for i in all_ids if i not in exercised]
    a(f"§5 defines **{len(all_ids)}** items; **{len(all_ids) - len(uncovered)}** are")
    a("exercised by a fixture. Uncovered: "
      + (", ".join(f"`{i}`" for i in uncovered) or "none")
      + ". That list is derived as `items − exercised`, not counted from")
    a("passing tests — a new item with no fixture would otherwise be invisible.")
    a("")

    a("## 5. Go compile gate")
    a("")
    a("`check_go_snippets.py` extracts every ```go block from the docs below,")
    a("wraps each in a package, and runs `go build`. A known-good package is")
    a("compiled first, so an environment failure reports INCOMPLETE (exit 3)")
    a("instead of blaming a snippet.")
    a("")
    # Imported, not regex-scraped: the previous version matched the first `]` in
    # `DOCS = [SKILL_DIR / "SKILL.md"] + sorted(...)` and reported that the gate
    # covered SKILL.md alone, understating its own coverage for months.
    go = load_module("rcs_gocheck_gen", SKILL_DIR / "scripts" / "check_go_snippets.py")
    names = [str(d.relative_to(SKILL_DIR)) for d in go.DOCS]
    a("Files covered: " + ", ".join(f"`{n}`" for n in names) + ".")
    a("")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    new = build()
    if args.check:
        old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if old != new:
            print("COVERAGE.md is out of date — run: python3 scripts/gen_coverage.py",
                  file=sys.stderr)
            return 1
        print("COVERAGE.md up to date")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUT.relative_to(SKILL_DIR)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
