-- V2 positive example: table creation in Oracle mode. All statements should succeed.
-- Prerequisite: Enterprise Edition + Oracle-compatibility-mode tenant. The Community Edition should skip this entirely (capability-matrix §0).
-- Key point: in Oracle mode, RANGE / LIST / HASH take a column list directly — **there is no COLUMNS keyword**.

-- 1) HASH: accepts a column list; multiple columns do not need KEY partitioning
CREATE TABLE T_HASH (
  USER_ID   NUMBER(20)   NOT NULL,
  NICK      VARCHAR2(64),
  CONSTRAINT PK_T_HASH PRIMARY KEY (USER_ID)
) PARTITION BY HASH(USER_ID) PARTITIONS 16;

CREATE TABLE T_HASH_MULTI (
  TENANT_ID VARCHAR2(32) NOT NULL,
  USER_ID   NUMBER(20)   NOT NULL,
  CONSTRAINT PK_T_HASH_MULTI PRIMARY KEY (TENANT_ID, USER_ID)
) PARTITION BY HASH(TENANT_ID, USER_ID) PARTITIONS 16;

-- 2) RANGE: single column
CREATE TABLE T_RANGE (
  ID      NUMBER(20) NOT NULL,
  TX_DATE DATE       NOT NULL,
  CONSTRAINT PK_T_RANGE PRIMARY KEY (ID, TX_DATE)
) PARTITION BY RANGE(TX_DATE) (
  PARTITION P2025 VALUES LESS THAN (TO_DATE('2026-01-01','YYYY-MM-DD')),
  PARTITION PMAX  VALUES LESS THAN (MAXVALUE)
);

-- 3) RANGE: **multiple columns are written directly inside RANGE** (corresponds to MySQL's RANGE COLUMNS)
CREATE TABLE T_RANGE_MULTI (
  TENANT_ID VARCHAR2(32) NOT NULL,
  STAT_DATE DATE         NOT NULL,
  CONSTRAINT PK_T_RANGE_MULTI PRIMARY KEY (TENANT_ID, STAT_DATE)
) PARTITION BY RANGE(TENANT_ID, STAT_DATE) (
  PARTITION P_A VALUES LESS THAN ('t50', TO_DATE('2026-01-01','YYYY-MM-DD')),
  PARTITION P_MAX VALUES LESS THAN (MAXVALUE, MAXVALUE)
);

-- 4) LIST: enumeration uses VALUES(...), **not** VALUES IN(...); DEFAULT as fallback
CREATE TABLE T_LIST (
  LOG_VALUE VARCHAR2(8) NOT NULL,
  ID        NUMBER(20)  NOT NULL,
  CONSTRAINT PK_T_LIST PRIMARY KEY (LOG_VALUE, ID)
) PARTITION BY LIST(LOG_VALUE) (
  PARTITION P01 VALUES ('A'),
  PARTITION P02 VALUES ('B'),
  PARTITION P_DEF VALUES (DEFAULT)
);

-- 5) LIST: multi-column enumeration
CREATE TABLE T_LIST_MULTI (
  REGION_CODE VARCHAR2(8) NOT NULL,
  BIZ_TYPE    VARCHAR2(8) NOT NULL,
  CONSTRAINT PK_T_LIST_MULTI PRIMARY KEY (REGION_CODE, BIZ_TYPE)
) PARTITION BY LIST(REGION_CODE, BIZ_TYPE) (
  PARTITION P1 VALUES (('01','A'), ('03','A')),
  PARTITION P_DEF VALUES (DEFAULT)
);

-- 6) INTERVAL: Oracle mode only, and accepts only a single column
CREATE TABLE T_INTERVAL (
  ID      NUMBER(20) NOT NULL,
  TX_DATE DATE       NOT NULL,
  CONSTRAINT PK_T_INTERVAL PRIMARY KEY (ID, TX_DATE)
) PARTITION BY RANGE(TX_DATE) INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) (
  PARTITION P1 VALUES LESS THAN (TO_DATE('2026-01-01','YYYY-MM-DD'))
);

-- 7) Templated second-level partitions
CREATE TABLE T_SUB_TPL (
  USER_ID NUMBER(20) NOT NULL,
  TX_DATE DATE       NOT NULL,
  BUCKET  NUMBER(10) NOT NULL,
  CONSTRAINT PK_T_SUB_TPL PRIMARY KEY (USER_ID, TX_DATE, BUCKET)
) PARTITION BY RANGE(TX_DATE)
  SUBPARTITION BY HASH(BUCKET) SUBPARTITION TEMPLATE (
    SUBPARTITION SP0, SUBPARTITION SP1, SUBPARTITION SP2, SUBPARTITION SP3
  ) (
  PARTITION P2025 VALUES LESS THAN (TO_DATE('2026-01-01','YYYY-MM-DD')),
  PARTITION PMAX  VALUES LESS THAN (MAXVALUE)
);

-- 8) Duplicated tables and queue tables (supported in both modes)
CREATE TABLE DIM_CURRENCY (
  CODE VARCHAR2(8) PRIMARY KEY,
  RATE NUMBER(18,8)
) DUPLICATE_SCOPE = 'cluster';

CREATE TABLE T_QUEUE (
  ID     NUMBER(20) PRIMARY KEY,
  STATUS NUMBER(3)
) TABLE_MODE = 'QUEUING';

-- 9) Auto-partitioning (in Oracle mode this is likewise a modifier clause on RANGE)
CREATE TABLE T_AUTOSPLIT (
  ID      NUMBER(20) NOT NULL,
  PAYLOAD VARCHAR2(128),
  CONSTRAINT PK_T_AUTOSPLIT PRIMARY KEY (ID)
) PARTITION BY RANGE(ID) SIZE('2G');

-- 10) Pure columnstore
CREATE TABLE T_COL (
  ID NUMBER(20) NOT NULL,
  D1 VARCHAR2(32), M1 NUMBER(18,2),
  CONSTRAINT PK_T_COL PRIMARY KEY (ID)
) WITH COLUMN GROUP(each column);
